### ISSUE TITLE
websockets failure

### ISSUE THREAD

**Issue by boydthomson** [ipsBruno/poloniex-trade-bot#11]
I'm getting an error from websockets.  I've tried installing ws@2 and ws@3 and reinstalling autobahn with npm.  I always get the following error:
   if (flags.binary) {
                     ^
TypeError: Cannot read property 'binary' of undefined
    at WebSocket.<anonymous> (/home/boyd/dev/poloniex-trade-bot/node_modules/autobahn/lib/transport/websocket.js:99:22)
Any suggestions would be most helpful, thank you.

**Comment by ipsBruno** [comment]
Veja aqui
https://github.com/crossbario/autobahn-js/issues/299
