### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by hugofurtad0** [ipsBruno/poloniex-trade-bot#13]
Alguém rodou em linux? Tenho um linux que fica on 24hrs, nele seria o ideal deixar fazendo trade, os computadores com windows não fica 24 horas ligados, dessa forma eu posso perde um operações. Alguém está rodando em linux?

**Comment by ipsBruno** [comment]
NodeJS é praticamente multi-plataforma. Portanto ele roda em Linux sim.
