### ISSUE TITLE
Erro TypeError: Cannot read property 'binary' of undefined

### ISSUE THREAD

**Issue by todiboa** [ipsBruno/poloniex-trade-bot#14]
Estou recebendo essa mensagem de erro logo que passa da informação "Recebendo informações sobre o preço", o que fazer?

**Comment by todiboa** [comment]
Este bot realiza a compra e vende de XMR em BTC e BTC em XMR?

**Comment by ipsBruno** [comment]
Você precisa configurar seus indicadores (programando) e a moeda para fazer pair trade

Sobre o erro é problema na biblioteca autobahn-js

Dê uma olhada
https://github.com/crossbario/autobahn-js/issues/299
