### ISSUE TITLE
Recebendo informações da sua conta ...

### ISSUE THREAD

**Issue by ctoveloz** [ipsBruno/poloniex-trade-bot#3]
Fica aparecendo apenas essa mensagem no cmd.
`Recebendo informações da sua conta ...`

Tenho o equivalente a `0.00141291 BTC` na poloniex
e configurei o valor de trader para` 0.05`

**Comment by jrcps** [comment]
Você precisa ter saldo em dólares para o bot operar, foi o único jeito que eu consegui fazer funcionar.

**Comment by ipsBruno** [comment]
Dependendo o modo de trader que tu escolher ele espera o mercado estiver "bom" pra criar posições
