### ISSUE TITLE
Bot nao realiza operacoes e retorna erro

### ISSUE THREAD

**Issue by waldirsp11** [ipsBruno/poloniex-trade-bot#5]
Configurei td certo com minha key, ai iniciei o bot, conforme log, e hora que ele foi tentar fazer uma compra, deu esse erro ... o que pode ser?

Nao fiz alteracao nenhuma no script, apenas o clone do repositorio.

          Sábado: 25/3/2017 @ 10:37:33   [start]         O BOT foi iniciado. Estou analisando mercado agora...
          Sábado: 25/3/2017 @ 10:37:43   [debug]         checkAccount >> started
          Sábado: 25/3/2017 @ 10:37:43   [debug]         advice >> updateBalance >> started
          Sábado: 25/3/2017 @ 10:37:43   [debug]         advice >> updateBalance >> Update completed | price: 0 | currency: 111.23780117 | asset: 0.00000000
          Sábado: 25/3/2017 @ 10:37:43   [info]          Saldo em USDT: 111.23780117
          Sábado: 25/3/2017 @ 10:37:43   [info]          Saldo em ETH:  0.00000000
          Sábado: 25/3/2017 @ 10:37:43   [debug]         profit.init >> started
          Sábado: 25/3/2017 @ 10:37:43   [debug]         profit.init >> initCurrecy: 111.23780117 | initAsset: 0.00000000
          Sábado: 25/3/2017 @ 10:37:43   [debug]         manipularOrdens >> started
          Sábado: 25/3/2017 @ 10:37:43   [debug]         manipularOrdens >> buyable: true
          Sábado: 25/3/2017 @ 10:37:43   [debug]         manipularOrdens >> Não existe nenhuma ordem aberta
          Sábado: 25/3/2017 @ 10:37:43   [debug]         advice >> opt >> started
          Sábado: 25/3/2017 @ 10:37:43   [debug]         advice >> opt >> Iniciando operação para: buy
          Sábado: 25/3/2017 @ 10:37:43   [debug]         advice >> updateBalance >> started
          Sábado: 25/3/2017 @ 10:37:43   [debug]         advice >> updateBalance >> Update completed | price: 0 | currency: 111.23780117 | asset: 0.00000000
          Sábado: 25/3/2017 @ 10:37:43   [debug]         advice >> calculate >> started
          Sábado: 25/3/2017 @ 10:37:43   [debug]         advice >> calculate >> calculo do ammount para compra
          Sábado: 25/3/2017 @ 10:37:43   [debug]         advice >> calculate >> exports.ammount: 2.28622629
          Sábado: 25/3/2017 @ 10:37:43   [debug]         advice >> buy >> started
          Sábado: 25/3/2017 @ 10:37:43   [debug]         advice >> buy >> price: 0 | ammount: 2.28622629
          **Sábado: 25/3/2017 @ 10:37:44   [error]         buy >> statusCode 422**

**Comment by ipsBruno** [comment]
@meirarc Código 422 o que deveria ser?

**Comment by criptonauta** [comment]
422 é o erro que a Polo retorna quando começa a exceder o limite do API de 6 calls/s. Se persiste, leva ao 429, que é um ban temporário.
