### ISSUE TITLE
O bot cobra por lucros?

### ISSUE THREAD

**Issue by todiboa** [ipsBruno/poloniex-trade-bot#7]

**Comment by todiboa** [comment]
Olá senhores, me diz uma coisa este bot cobra por lucros ou ele é gratuito?

Poderiam me informar?

**Comment by neomvll** [comment]
Mesma dúvida.

**Comment by ipsBruno** [comment]
Não cobra não. O BOT é open-source e cada um usa ao gosto que tiver.
