### ISSUE TITLE
linux / RPi

### ISSUE THREAD

**Issue by neomvll** [ipsBruno/poloniex-trade-bot#8]
Olá, Roda em linux? raspbian pra ser mais exato

**Comment by boydthomson** [comment]
Can you run javascript on Raspbian?  If you can't answer that question for yourself, you might want to reconsider trying to use this code to trade with your money.  Take an intro to JavaScript tutorial and go from there.
Hope that helps, good luck.

**Comment by ipsBruno** [comment]
É possível rodar e RaspBy sim

Você só vai precisar instalar o NodeJS corretamente nele.

É Linux
